modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/NinjaPhenix/expanded-storage/issues/"
license = "multiple"

[[mods]]
modId = "expandedstorage"
version = "${version}"
displayName = "Expanded Storage"
authors = "NinjaPhenix"
logoFile = "icon.png"

[[dependencies.expandedstorage]]
modId = "forge"
mandatory = true
versionRange = "[40.0.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.expandedstorage]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.expandedstorage]]
modId = "ninjaphenix_container_lib"
mandatory = true
versionRange = "[1.3.0,)"
ordering = "NONE"
side = "BOTH"
